
export const CREATE_EVENT = 'CREATE_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'
export const DELETE_ALL_EVENT = 'DELETE_ALL_EVENT'

export const ADD_OPERATION_LOG = 'ADD_OPERATION_LOG'
export const DELETE_OPERATION_LOGS = 'DELETE_OPERATION_LOGS'